[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#cdd6f4"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = "#45475A" # surface1
red = "#F38BA8" # red
green = "#A6E3A1" # green
yellow = "#F9E2AF" # yellow
blue = "#89B4FA" # blue
magenta = "#F5C2E7" # pink
cyan = "#94E2D5" # teal
white = "#BAC2DE" # subtext1

[colors.bright]
black = "#585B70" # surface2
red = "#F38BA8" # red
green = "#A6E3A1" # green
yellow = "#F9E2AF" # yellow
blue = "#89B4FA" # blue
magenta = "#F5C2E7" # pink
cyan = "#94E2D5" # teal
white = "#A6ADC8" # subtext0

[colors.dim]
black = "#45475A" # surface1
red = "#F38BA8" # red
green = "#A6E3A1" # green
yellow = "#F9E2AF" # yellow
blue = "#89B4FA" # blue
magenta = "#F5C2E7" # pink
cyan = "#94E2D5" # teal
white = "#BAC2DE" # subtext1

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"
